apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
{{- include "spring.labels" . | nindent 3}}
data:
  dbname: {{ .Values.database_prod.dbname }}
  dbtable: {{ .Values.database_prod.dbtable }}
  image: {{ .Values.pods.image }}:{{ .Values.pods.tag }}
  drink: {{ .Values.food.drink | upper }}
  eat: {{ .Values.food.eat | trunc 13 | upper | quote }}
