apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version }}
  labels:
{{- include "spring.labels" . | nindent 4}}
spec:
  selector: 
    matchLabels:
      {{- include "spring.labels" . | nindent 6}}  
  replicas: {{ .Values.appenv.replicas }}
  template:
    metadata:
      labels:
        {{- include "spring.labels" . | nindent 8}}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.pod.image }}:{{ .Values.pod.imagetag }}
        ports:
        - containerPort: {{ .Values.appenv.targetPort }}
