kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Release.Name }}-service
  labels:
  {{- include "spring.labels" . | nindent 4}}
spec:
  selector:
    {{- include "spring.labels" . | nindent 4}}
  {{ if eq .Values.env "LOCAL" }}
  type: NodePort  #from values | DEFAULT TO NODEPORT
  {{ else if eq .Values.env "AWS"}}
  type: LoadBalancer
  {{ end }}
  ports:         
  - name: http   
    protocol: TCP
    port: {{ .Values.appenv.port }}
    targetPort: {{ .Values.appenv.targetPort }}
