apiVersion: v1
kind: Service
metadata:
  name: animal-svc
  labels:
    app-svc: animals
spec:
  selector:
    app: animals
  ports:
  - name: http-web
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https-management
    protocol: TCP
    port: 443
    targetPort: 9443
  type: LoadBalancer