apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-bear
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: animals
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80