apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-mmose
  labels:
    app: app2
spec:
  selector:
    matchLabels:
      app: animals
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80