database_prod:
  dbname: db_mysql
  dbtable: music
database_test:
  dbname: db_mysql-test
  dbtable: music
pods:
  image: yanivomc/springmusic
  tag: latest
food:
  drink: beer
  eat: Peanut Butter and Jelly Sandwich
